services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_service

    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.external-url=http://localhost:7070/prometheus/"
      - "--web.route-prefix=/"

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    restart: unless-stopped

    networks:
      - platform-network

  # Node exporter to monitor system wide metrics
  node_exporter:
    image: prom/node-exporter:master-distroless
    container_name: node_exporter_service
    command:
      - "--path.rootfs=/host"

    restart: unless-stopped

    pid: host
    volumes:
      - "/:/host:ro,rslave"

    networks:
      - platform-network


volumes:
  prometheus-data:
    external: true

networks:
  platform-network:
    driver: bridge
    external: true