services:
  cdc-postgres:
    image: postgres:16
    container_name: cdc_postgres

    environment:
      POSTGRES_USER: cdc
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cdc_db

    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_replication_slots=10
      - -c
      - max_wal_senders=10

    volumes:
      - cdc_data:/var/lib/postgresql/data
    networks:
      - platform-network

    restart: unless-stopped

    ports:
      - "5434:5432"

    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: docker.aqi_database

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "cdc", "-d", "cdc_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


  replication-postgres:
    image: postgres:16
    container_name: replication_postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rep_db

    networks:
      - platform-network

    restart: unless-stopped

    ports:
      - "5435:5432"

    depends_on:
      - cdc-postgres

    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: docker.replication_database

    volumes:
      - replication_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "rep_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s


networks:
  platform-network:
    driver: bridge
    external: true

volumes:
  cdc_data:
    external: true

  replication_data:
    external: true