services:
    alloy:
      image: grafana/alloy:v1.18.0-rc.0
      container_name: grafana_alloy_service
      restart: unless-stopped
      networks:
        - platform-network
      volumes:
        - ./config.alloy:/etc/alloy/config.alloy

      env_file:
        - ../../.env

      ports:
        - "12345:12345"

      expose:
        - "9999"

      command:
        - run
        - /etc/alloy/config.alloy
        - --server.http.listen-addr=0.0.0.0:12345
        - --storage.path=/var/lib/alloy/data

networks:
  platform-network:
    driver: bridge
    external: true