services:
  kafka:
    image: apache/kafka:4.3.1
    container_name: kafka_service
    volumes:
      - kafka_data:/var/lib/kafka/data
    ports:
      - "9092:9092" # Internal Docker listerners
      - "29092:29092" # External Host listerners
      - "9093:9093"
    restart: unless-stopped
    networks:
      - platform-network

    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: docker.kafka

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093, HOST://:29092"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,HOST:PLAINTEXT"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_BROKER_ID: 1
      KAFKA_COMPRESSION_TYPE: "zstd"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"


networks:
  platform-network:
    driver: bridge
    external: true

volumes:
  kafka_data:
    external: true