services:
  postgres-consumer:
    build:
      context: ../../
      dockerfile: containers/postgres_consumer/Dockerfile
    container_name: postgres_consumer
    
    networks:
      - platform-network

    env_file:
      - ../../.env

    logging:
      driver: "fluentd"
      options:
        fluentd-address: "localhost:24224"
        tag: docker.postgres_consumer

    restart: unless-stopped

networks:
  platform-network:
    driver: bridge
    external: true